[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    crankyoldgit/IRremoteESP8266
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP